[package]
name = "snow"
description = "A pure-rust implementation of the Noise Protocol Framework"
homepage = "https://github.com/mcginty/snow"
repository = "https://github.com/mcginty/snow"
version = "0.1.0-preview"
authors = ["Jake McGinty <me@jake.su>", "trevp"]
license = "Unlicense"
categories = ["cryptography"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto"]

[features]
default = []
vector-tests = []

[badges]
travis-ci = { repository = "mcginty/snow", branch = "master" }

[dependencies]
arrayvec = "^0.3"
error-chain = "^0.10"
rust-crypto = "0.2.36"
byteorder = "^1.0"
rand = "^0.3"
static_slice = "0.0.3"

[dependencies.blake2-rfc]
version = "^0.2.17"
features = ["simd_opt"]

[dependencies.chacha20-poly1305-aead]
version = "^0.1.2"
features = ["simd_opt"]

[dev-dependencies]
clap = "^2.0"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "1.0"
hex = "0.2.0"
