[package]
name = "snow"
description = "A pure-rust implementation of the Noise Protocol Framework"
homepage = "https://github.com/mcginty/snow"
repository = "https://github.com/mcginty/snow"
version = "0.0.1-preview.0"
authors = ["trevp", "mcginty"]
license = "Unlicense"

[dependencies]
arrayvec = "^0.3"
rust-crypto = "*"
byteorder = "*"
rand = "0.3"
rustc-serialize = "0.3"
static_slice = "0.0.2"

[dependencies.blake2-rfc]
version = "^0.2.17"
features = ["simd_opt"]

[dependencies.chacha20-poly1305-aead]
version = "^0.1.2"
features = ["simd_opt"]

[dev-dependencies]
clap = "^2.0"
