[package]
name = "snow"
version = "0.0.1-preview.0"
authors = ["trevp", "mcginty"]

[dependencies]
arrayvec = "^0.3"
rust-crypto = "*"
byteorder = "*"
rand = "0.3"
rustc-serialize = "0.3"
static_slice = "0.0.2"

[dependencies.blake2-rfc]
version = "^0.2.17"
features = ["simd_opt"]

[dependencies.chacha20-poly1305-aead]
version = "^0.1.2"
features = ["simd_opt"]

[dev-dependencies]
clap = "*"
